# Generated by Django 5.0.2 on 2024-02-18 09:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hbdhvc', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='content',
            new_name='message',
        ),
    ]
